# Generated by Django 2.1 on 2018-08-26 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0002_remove_user_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
