# Generated by Django 2.1 on 2018-08-25 17:23

from django.db import migrations, models
import sponsors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('question', models.TextField(max_length=100)),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to=sponsors.models.get_upload_url)),
            ],
            options={
                'verbose_name_plural': 'Sponsors',
            },
        ),
    ]
