# Generated by Django 2.1 on 2018-08-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='question',
            new_name='description',
        ),
    ]
