# Generated by Django 2.1.2 on 2019-08-26 19:36

from django.db import migrations, models
import userAccounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0003_auto_20180827_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, upload_to=userAccounts.models.get_upload_url),
        ),
    ]
