# File structure version
version: '3'

services:
  # Database based on official postgres image
  db:
    image: postgres
    hostname: db

  # Our django application
  # Build from remote dockerfile
  # Connect local app folder with image folder, so changes will be pushed to image instantly
  # Open port 8000
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - ./static:/static
    expose:
      - "8000"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - app