# Generated by Django 2.1 on 2018-08-25 17:23

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('question', models.TextField(max_length=500)),
                ('answer', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to=questions.models.get_upload_url)),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
